apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmapdemo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmapdemo
  template:
    metadata:
      labels:
        app: configmapdemo
    spec:
      containers:
        - name: configmapdemo-container
          image: docker.io/library/configmapdemo:0.0.1
          # Bring key:value pairs in as environment variables 
          # from the config map. Note: all key:value pairs will
          # become environment variables.
          # You can bring in secrets as well via secretRef. The
          # secret must be in the same namespace. If there is a 
          # conflict between a secret and a config map, the order
          # below will determine which is used.
          envFrom:
          - configMapRef:
              name: my-literal-config
          # Bring key:value pairs in as a properties file from 
          # config map (see also: volumes) and mount the file
          # in /etc/config (dir will be created if it doesn't 
          # exist, I think)
          volumeMounts:
          - name: configmap-volume
            mountPath: /etc/config
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
      volumes:
        - name: configmap-volume
          configMap: 
            name: my-literal-config
            items:
            # Name of data item in the config map.
            - key: configmapdemo.properties
            # Name of the mounted file in the container.
            # If this is not specified, a file will be made 
            # out of ALL data items in the config map.
              path: configmapdemo.properties
