apiVersion: v1
kind: ConfigMap
metadata:
    name: my-literal-config
data:
    DEMO_ENVIRONMENT_STRING: "This is from an environment variable in a ConfigMap"
    configmapdemo.properties: |
        demo.file.string=This is from a file in a ConfigMap